#!/usr/bin/env bash
# installing nginx on the web-01 server
apt-get -y update
apt-get -y install nginx
mv /usr/share/nginx/html/index.html /usr/share/nginx/html/index.html.bak
echo "Hello World!" > /usr/share/nginx/html/index.html
NGINX_CONF="/etc/nginx/nginx.conf"
cp "$NGINX_CONF" "$NGINX_CONF.bak"
sed -i 's/listen\s*\(.*\);/listen 80;/g' "$NGINX_CONF"
service nginx restart
