#!/usr/bin/env bash
# Script that configure HAproxy on your lb-01 server.

apt-get update
apt-get install -y haproxy
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.default
echo "
listen 132320-lb-01
        bind *:80
        mode http
        balance roundrobin
        option httpclose
        option forwardfor
        server 132320-web-01 54.173.175.228 check
        server 132320-web-02 52.73.248.17 check
" >> /etc/haproxy/haproxy.cfg
service haproxy restart