#!/usr/bin/env bash

# MySQL credentials
MYSQL_USER="root"      # Replace with your MySQL username with administrative privileges
MYSQL_PASSWORD="0700479408"  # Replace with your MySQL root password

# MySQL user details
NEW_USER="holberton_user"
NEW_USER_PASSWORD="projectcorrection280hbtn"
HOSTNAME="localhost"

# Execute MySQL queries
mysql -u "$MYSQL_USER" -p"$MYSQL_PASSWORD" <<EOF
CREATE USER IF NOT EXISTS '$NEW_USER'@'$HOSTNAME' IDENTIFIED BY '$NEW_USER_PASSWORD';
GRANT REPLICATION CLIENT ON *.* TO '$NEW_USER'@'$HOSTNAME';
FLUSH PRIVILEGES;
EOF

# Check if user creation was successful
if [ $? -eq 0 ]; then
  echo "MySQL user '$NEW_USER' with host '$HOSTNAME' was created successfully."
else
  echo "Error creating MySQL user."
fi
